inference_classes:
    - abbreviation
    - aircraft
    - airfare
    - airline
    - airport
    - capacity
    - cheapest
    - city
    - distance
    - flight
    - flight number
    - flight time
    - ground fare
    - ground service
    - meal
    - quantity
    - restriction
